name: if example
on:
  push:
    branches:
      - main
      - develop
      - feature/**
jobs:
  quality_checks:
    if: startsWith(github.ref_name,'feature') && github.event_name=='push'
    runs-on: ubuntu-latest
    steps:
      - name: run quality quality checks
        run: |
        echo "Performing quality checks"
        exit 1


  dev_deploy:
    if: github.ref_name=='develop' && github.event_name=='push'
    runs-on: ubuntu-latest
    steps:
      - name: dev deploy
        run: echo "code deploy to the developement deployment"


  prod_deploy:
    if: github.ref_name=='main' && github.event_name=='push'
    runs-on: ubuntu-latest
    steps:
      - name: production deploy
        run: echo "code deploy to the Production deployment"


  Success_Notify:
    needs: ["quality_checks","dev_deploy","prod_deploy"]
    if: always() && !failure()
    runs-on: ubuntu-latest
    steps:
      - name: Success_Notify
        run: echo "Successfull email sent to the team"



  failure_Notify:
    needs: ["quality_checks","dev_deploy","prod_deploy"]
    if: failure()
    runs-on: ubuntu-latest
    steps:
      - name: Failure Notify
        run: echo "Successfull email sent to the team"