name: reusable workflow
on:
  workflow_call:
jobs:
  greeting:
    
    runs-on: ubuntu-latest
    steps:
      - name: Greetings step
        run:  echo "Performing reusable workflow call"
          
